.TH WARCSUM 1
.SH NAME
warcsum \- reads multimember warc files and generates digest for the
http response members.
.SH SYNOPSIS
.B warcsum
[\fB\-i\fR \fIFILE\fR]
[\fB\-o\fR \fIFILE\fR]
[\fB\-h\fR \fIHASH ALGO\fR]
[\fB\-n\fR \fIInput buffer size\fR]
[\fB\-u\fR \fIOutput buffer size\fR]
\fB\-a\fR
\fB\-f\fR
\fB\-v\fR

.SH DESCRIPTION

warcsum takes as processes a multimember (or a single member) warcfile
and produces digest file of all members in the file. The digest file
consists of a single line describing each response member whose response
type is http.

A digest line typically contains the following fields:
<WARC filename> <member offset> <member end> <URI> <date> <hash digest>

.SH OPTIONS
.TP
.BR \-i ", " \-\-input =\fIFILE\fR
Path to warcfile.
.TP
.BR \-o ", " \-\-ouput =\fIFILE\fR
Path to digest file.
.TP
.BR \-I ", " \-\-input-buffer =\fISIZE\fR
Initial uncompressed buffer size, if size is not sufficient to fit the headers,
buffer size is doubled. It can be written in Bytes (default), Kilobytes, 
Megabytes, or Gigabytes, as illustrated in \fBEXAMPLES\fR.
.TP
.BR \-O ", " \-\-ouput-buffer =\fISIZE\fR
Path to digest file.
.TP
.BR \-H ", " \-\-hash =\fIHASHING_ALGORITHM\fR
Hashing algorithm to be used for hashing the warc member payload.
Possible options are \fImd5\fR, \fIsha1\fR, \fIsha256\fR or \fIsha512\fR. The default
option is \fIsha1\fR.
.TP
.BR \-f ", " \-\-force
Force recalculate hash and discard stored hash in the WARC member
header. If \fB\-\-hash\fR option was supplied and hash type is not
\fIsha1\fR, hash is recalculated by default.
.TP
.BR \-a ", " \-\-append
Append to output file instead of rewriting it.
.TP
.BR \-v ", " \-\-verbose
Explain what is being done.

.SH EXAMPLES
warcsum -i input.warc.gz -h sha1 -I 8192 -O 16384 -o digest -fv

warcsum -i input.warc.gz -h sha1 -I 8K -O 16K -o digest -a

.SH COPYRIGHT
Copyright (C) 2015 Bibliotheca Alexandrina

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

This program acts as the first step in arcalex project.

Given a compressed multimember warc.gz (or a singlemember warc.gz)
file,
this program calculates its digest and appends it to given digests
file.
.TP
Manifest contains following data:
     1. Warc file name
     2. Offset (compressed)
     3. End (compressed)
     4. URI
     5. Date
     6. Digest
