.TH WARCSUM 1
.SH NAME
warcsum \- reads multimember warc files and generates digest for the
http response members.
.SH SYNOPSIS
.B warcsum
\fB\--input\fR=\fIfile\fR
\fB\--output\fR=\fIfile\fR
[\fB\--hash\fR=\fIalgorithm\fR]
[\fB\--input-buffer\fR \fIsize\fR]
[\fB\--output-buffer\fR \fIsize\fR]
[\fB\--recursive\fR]
[\fB\--append\fR]
[\fB\--force\fR]
[\fB\--verbose\fR]
[\fB\--quite\fR]
[\fB\--skip-empty\fR]

.SH DESCRIPTION

warcsum takes as processes a multimember (or a single member) warcfile
or a directory if operated in recursive mode, and produces digest file 
of all members in the file. The digest file consists of a single line 
describing each response member whose response type is http.

A digest line typically contains the following fields:
<WARC filename> <member offset> <member end> <URI> <date> <hash digest>

.SH OPTIONS
.TP
.BR \-i ", " \-\-input =\fIfile\fR
Path to WARC file or directory.
.TP
.BR \-o ", " \-\-ouput =\fIfile\fR
Path to digest file.
.TP
.BR \-I ", " \-\-input-buffer =\fIsize\fR
Initial uncompressed input buffer size, if size is not sufficient to fit the 
headers, buffer size is doubled. It can be written in Bytes (default), Kilobytes, 
Megabytes, or Gigabytes, as illustrated in \fBEXAMPLES\fR.
.TP
.BR \-O ", " \-\-ouput-buffer =\fIsize\fR
Initial uncompressed output buffer size, if size is not sufficient to fit the 
headers, buffer size is doubled. It can be written in Bytes (default), Kilobytes, 
Megabytes, or Gigabytes, as illustrated in \fBEXAMPLES\fR.
.TP
.BR \-H ", " \-\-hash =\fIalgorithm\fR
Algorithm to be used for hashing the warc member payload.
Possible options are \fImd5\fR, \fIsha1\fR, \fIsha256\fR or \fIsha512\fR. The default
option is \fIsha1\fR.
.TP
.BR \-f ", " \-\-force
Force recalculate hash and discard stored hash in the WARC member
header. If \fB\-\-hash\fR option was supplied and hash type is not
\fIsha1\fR, hash is recalculated by default.
.TP
.BR \-a ", " \-\-append
Append to output file instead of rewriting it.
.TP
.BR \-v ", " \-\-verbose
Explain what is being done.

.SH EXAMPLES
warcsum -i input.warc.gz -h sha1 -I 8192 -O 16384 -o digest -fv

warcsum -i input.warc.gz -h sha1 -I 8K -O 16K -o digest -a

.SH COPYRIGHT
Copyright (C) 2015 Bibliotheca Alexandrina

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.